apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-maven
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
     path: /data/k8s-share/mvncache
     server: 192.168.32.12
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-maven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
