kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shenzhen
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1beta1 
kind: RoleBinding
metadata:
  name: clusterrole-bind-shenzhen
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: shenzhen
  namespace: test
